# Generated by Django 3.1 on 2020-08-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_image_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.CharField(default='A little about me....', max_length=140),
        ),
    ]
